version: "3.8"

services:
  app:
    container_name: wedeal_dev
    image: wedeal_dev
    build:
      context: ../
      dockerfile: ./docker/dev.Dockerfile
    volumes:
      - ../.:/go/src/github.com/vinicius98s/wedeal
    ports:
      - 8080:8080
    env_file:
      - ../.env
