version: "3.8"

services:
  app:
    container_name: wedeal-dev
    image: wedeal-dev
    build:
      context: ../
      dockerfile: ./docker/dev.Dockerfile
    volumes:
      - ../.:/go/src/github.com/vinicius98s/wedeal
    ports:
      - 8080:8080
    env_file:
      - ../.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - 27018:27017
    logging:
      driver: none
